# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBj1t67L_HItjjfFKVn-0_Iqpu2WUNXU
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("66.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm2= cv2.imread("/content/images (3).jfif")
cv2_imshow(rasm2)

oqqora= cv2.cvtColor(rasm2, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm3= cv2.imread("3. Леопард.jpg")
cv2_imshow(rasm3)

oqqora= cv2.cvtColor(rasm3, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm4= cv2.imread("/content/17. Мост.jpg")
cv2_imshow(rasm4)

oqqora= cv2.cvtColor(rasm4, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm5= cv2.imread("/content/images.jfif")
cv2_imshow(rasm5)

oqqora= cv2.cvtColor(rasm5, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)